FROM openjdk:11-jdk

# COPY ./build/libs/<프로젝트명>-<버전>-SNAPSHOT.jar app.jar
ARG JAR_FILE=./build/libs/haemil-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=dev", "/app.jar"]