# RDS Config
spring:
  datasource:
    url: jdbc:mysql://db:3306/haemildb?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: admin
    password: haemil4720!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always

# Redis Config
redis:
  host: redis
  port: 6379

# Swagger Config