# AWS RDS
spring:
  datasource:
    url: jdbc:mysql://haemil-database.c1sdlxnpiryp.ap-northeast-2.rds.amazonaws.com/main_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: haemil1237
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          format_sql: true

# security config
jwt:
  # secret-key
  secret-key: ASDFOPHdsajkgyuoDSFipay7f0eFwqHuhaemiljroiasDSadfoiBoiAWEytfuiaDasdoFifdguHHeaaGFsZ2VvFSeW8K
  # 90일
  cookie-period: 7776000
  # refresh: 7일
  refresh-period: 604800000
  # access: 30분
  access-period: 1800000
api:
  secret-key: "%2FBPEf21bFPV0445%2BLOonhH%2FSRSeCQbynMAro8sHgomFg03OmuxifwF%2Bnl%2Fz7Nj%2FGXVpYydUdPSYwuywH0eErqw%3D%3D"
  hj-secret-key: "Zj0sLbMrwO6sNx5VVTO1ExwsGaiiab7foNhOtvUgNrl/S2AeCLt1o2B4EzZEaYBg/OsM0vkFjuhttPUq3vbq6A=="
  hj-kakao-key: "88102d82e2851449e4fc7757d6d0f9b6"
  kakao-rest-api-key: "88102d82e2851449e4fc7757d6d0f9b6"
oauth:
  kakao:
    client-id: 88102d82e2851449e4fc7757d6d0f9b6
    client-secret: UUcKsBCD4WzSFLbL5Fgx2VhpBA1QgiDp
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  google:
    client-id:
    client-secret: