# AWS RDS
spring:
  datasource:
    url: jdbc:mysql://haemil-mysql-instance.c02to6wghrct.ap-northeast-2.rds.amazonaws.com:3306/main_table?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: haemil4720!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          format_sql: true

# security config
jwt:
  # secret-key
  secret-key:
  # refresh: 7일
  refresh-period: 604800000
  # access: 30분
  access-period: 1800000
api:
  secret-key: "%2FBPEf21bFPV0445%2BLOonhH%2FSRSeCQbynMAro8sHgomFg03OmuxifwF%2Bnl%2Fz7Nj%2FGXVpYydUdPSYwuywH0eErqw%3D%3D"
  hj-secret-key: "Zj0sLbMrwO6sNx5VVTO1ExwsGaiiab7foNhOtvUgNrl/S2AeCLt1o2B4EzZEaYBg/OsM0vkFjuhttPUq3vbq6A=="

oauth:
  kakao:
    client-id: cf552915e52ec7012b72a272c81c1244
    client-secret: UUcKsBCD4WzSFLbL5Fgx2VhpBA1QgiDp
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  google:
    client-id:
    client-secret: