# RDS Config
spring:
  datasource:
    url: jdbc:mysql://haemil-mysql-instance.c02to6wghrct.ap-northeast-2.rds.amazonaws.com:3306/haemil-mysql-instance
    username: admin
    password: haemil4720!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always

# Redis Config
redis:
  host: redis
  port: 6379

# Swagger Config