name: google-java-format

on: [ push, pull_request ]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        id: format-check
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed --fix-imports-only"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print diffs
        run: git --no-pager diff --exit-code
