name: google-java-format

on: [ push, pull_request ]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Selected Files
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's#refs/heads/##')
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Branch Name: $BRANCH_NAME"
          echo "Setting FILE_PATTERN variable"
          echo "FILE_PATTERN=${GITHUB_WORKSPACE}/src/main/java/com/haemil/backend/${BRANCH_NAME}/*" >> $GITHUB_ENV
      
      - name: Check formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit: true
          files: "${{ env.FILE_PATTERN }}"
          
      - name: Print diffs
        run: git --no-pager diff --exit-code

