name: google-java-format

on: [ push, pull_request ]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "set-exit-if-changed --fix-imports-only"
          commit-message: "format: Google Java Format"
					github-token: ${{ secrets.GH_TOKEN }}
