name: google-java-format

on: [ push, pull_request ]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit: true
          files: "${{ env.GITHUB_WORKSPACE }}/src/main/java/com/haemil/backend/${{GITHUB_REF#refs/heads/}}/*"
          
      - name: Print diffs
        run: git --no-pager diff --exit-code

